BloodDonationSystem/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('backend', admin.site.urls),
    path('donator/', include('donator.urls')),
    path('receiver/', include('receiver.urls')),
    path('accounts/', include('accounts.urls')),
    path('', include('home.urls')),
]

accounts/urls.py
from django.urls import path, include

from accounts.views import register, DashboardView, DonatorReceiverDashboardView, loginRequest

app_name = 'Accounts'
urlpatterns = [
    path('register', register, name='register'),
    path('login', loginRequest, name='login'),
    path('dashboard', DashboardView.as_view(), name='dashboard'),
    path('user_dashboard', DonatorReceiverDashboardView.as_view(), name='user_dashboard')
]

home/urls.py
from django.urls import path

from home.views import IndexView
app_name = 'Home'
urlpatterns = [
    path('',IndexView.as_view(),name='start_page')
]

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render

# Create your views here.
from django.views.generic import TemplateView


class IndexView(TemplateView):
    template_name = 'home_index.html'

home/templates/home_index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Blood Donation System</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css?family=Dosis:200,300,400,500,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Overpass:300,400,400i,600,700" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'start_page/css/open-iconic-bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'start_page/css/animate.css' %}">

    <link rel="stylesheet" href="{% static 'start_page/css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'start_page/css/owl.theme.default.min.css' %}">
    <link rel="stylesheet" href="{% static 'start_page/css/magnific-popup.css' %}">

    <link rel="stylesheet" href="{% static 'start_page/css/aos.css' %}">

    <link rel="stylesheet" href="{% static 'start_page/css/ionicons.min.css' %}">

    <link rel="stylesheet" href="{% static 'start_page/css/bootstrap-datepicker.css' %}">
    <link rel="stylesheet" href="{% static 'start_page/css/jquery.timepicker.css' %}">


    <link rel="stylesheet" href="{% static 'start_page/css/flaticon.css' %}">
    <link rel="stylesheet" href="{% static 'start_page/css/icomoon.css' %}">
    <link rel="stylesheet" href="{% static 'start_page/css/style.css' %}">
  </head>
  <body>

  <nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light" id="ftco-navbar">
    <div class="container">
      <a class="navbar-brand" href="home_index.html">Blood Donation System</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="oi oi-menu"></span> Menu
      </button>

      <div class="collapse navbar-collapse" id="ftco-nav">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item active"><a href="{% url 'Home:start_page' %}" class="nav-link">Home</a></li>
          <li class="nav-item"><a href="{% url 'Accounts:login' %}" class="nav-link">Login</a></li>
          <li class="nav-item"><a href="{% url  'Accounts:register'%}" class="nav-link">Register</a></li>
        </ul>
      </div>
    </div>
  </nav>
    <!-- END nav -->

    <div class="hero-wrap" style="background-image: url({% static 'start_page/images/bg_7.jpg' %});" data-stellar-background-ratio="0.5">
      <div class="overlay"></div>
      <div class="container">
        <div class="row no-gutters slider-text align-items-center justify-content-center" data-scrollax-parent="true">
          <div class="col-md-7 ftco-animate text-center" data-scrollax=" properties: { translateY: '70%' }">
            <h1 class="mb-4" data-scrollax="properties: { translateY: '30%', opacity: 1.6 }">Doing Nothing is Not An Option of Our Life</h1>

          </div>
        </div>
      </div>
    </div>

    <section class="ftco-counter ftco-intro" id="section-counter">
    	<div class="container">
    		<div class="row no-gutters">
    			<div class="col-md-5 d-flex justify-content-center counter-wrap ftco-animate">
            <div class="block-18 color-1 align-items-stretch">
              <div class="text">
              	<span>Served Over</span>
                <strong class="number" data-number="200">0</strong>
                <span>Serving Many in the country</span>
              </div>
            </div>
          </div>
          <div class="col-md d-flex justify-content-center counter-wrap ftco-animate">
            <div class="block-18 color-2 align-items-stretch">
              <div class="text">
              	<h3 class="mb-4">Donate Blood</h3>
              	<p>Even the all-powerful Pointing has no control about the blind texts.</p>
              	<p><a href="{% url 'Accounts:register' %}" class="btn btn-white px-3 py-2 mt-2">Donate Now</a></p>
              </div>
            </div>
          </div>
          <div class="col-md d-flex justify-content-center counter-wrap ftco-animate">
            <div class="block-18 color-3 align-items-stretch">
              <div class="text">
              	<h3 class="mb-4">Be a Donor</h3>
              	<p>Help save a life by donating blood to those in dire need for the blood donation.</p>
              	<p><a href="{% url 'Accounts:register' %}" class="btn btn-white px-3 py-2 mt-2">Be A Volunteer</a></p>
              </div>
            </div>
          </div>
    		</div>
    	</div>
    </section>

    <section class="ftco-section">
    	<div class="container">
    		<div class="row">
          <div class="col-md-4 d-flex align-self-stretch ftco-animate">
            <div class="media block-6 d-flex services p-3 py-4 d-block">
              <div class="icon d-flex mb-3"><span class="flaticon-donation-1"></span></div>
              <div class="media-body pl-4">
                <h3 class="heading">Make Donation</h3>
                <p>SIgn Up and view the ones in need for the donation. Donate to save a life</p>
              </div>
            </div>
          </div>
          <div class="col-md-4 d-flex align-self-stretch ftco-animate">
            <div class="media block-6 d-flex services p-3 py-4 d-block">
              <div class="icon d-flex mb-3"><span class="flaticon-charity"></span></div>
              <div class="media-body pl-4">
                <h3 class="heading">Become A Volunteer</h3>
                <p>Help the patients in dire need of the blood</p>
              </div>
            </div>
          </div>
          <div class="col-md-4 d-flex align-self-stretch ftco-animate">
            <div class="media block-6 d-flex services p-3 py-4 d-block">
              <div class="icon d-flex mb-3"><span class="flaticon-donation"></span></div>
              <div class="media-body pl-4">
                <h3 class="heading">Receive</h3>
                <p>Get the donators who match your blood type and get a donation from them</p>
              </div>
            </div>
          </div>
        </div>
    	</div>
    </section>







		<section class="ftco-section-3 img" style="background-image: url({% static 'start_page/images/bg_3.jpg' %});">
    	<div class="overlay"></div>
    	<div class="container">
    		<div class="row d-md-flex">
    		<div class="col-md-6 d-flex ftco-animate">
    			<div class="img img-2 align-self-stretch" style="background-image: url({% static 'start_page/images/bg_4.jpg' %});"></div>
    		</div>
    		<div class="col-md-6 volunteer pl-md-5 ftco-animate">
    			<h3 class="mb-3">Be a Donator</h3>
    			<form action="#" class="volunter-form">
            <div class="form-group">
              <input type="text" class="form-control" placeholder="Your Name">
            </div>
            <div class="form-group">
              <input type="text" class="form-control" placeholder="Your Email">
            </div>
            <div class="form-group">
              <textarea name="" id="" cols="30" rows="3" class="form-control" placeholder="Message"></textarea>
            </div>
            <div class="form-group">
                <a href="{% url  'Accounts:register' %}"  class="btn btn-white py-3 px-5">Submit</a>
            </div>
          </form>
    		</div>
    		</div>
    	</div>
    </section>

    <footer class="ftco-footer ftco-section img">
    	<div class="overlay"></div>
      <div class="container">
        <div class="row mb-5">
          <div class="col-md-3">
            <div class="ftco-footer-widget mb-4">
              <h2 class="ftco-heading-2">About Us</h2>
              <p>We help link the patients that need a lot of blood and those who potentially need the blood. Access our account and help make change in the community</p>
              <ul class="ftco-footer-social list-unstyled float-md-left float-lft mt-5">
                <li class="ftco-animate"><a href="#"><span class="icon-twitter"></span></a></li>
                <li class="ftco-animate"><a href="#"><span class="icon-facebook"></span></a></li>
                <li class="ftco-animate"><a href="#"><span class="icon-instagram"></span></a></li>
              </ul>
            </div>
          </div>
          <div class="col-md-4">
            <div class="ftco-footer-widget mb-4">
              <h2 class="ftco-heading-2">Recent Donations</h2>
              <div class="block-21 mb-4 d-flex">
                <a class="blog-img mr-4" style="background-image: url({% static 'start_page/images/image_1.jpg' %});"></a>
                <div class="text">
                  <h3 class="heading"><a href="#">A donation done in the counties</a></h3>
                  <div class="meta">
                    <div><a href="#"><span class="icon-calendar"></span> February 4, 2020</a></div>
                    <div><a href="#"><span class="icon-person"></span> Edwin Kimani</a></div>
                    <div><a href="#"><span class="icon-chat"></span> 1</a></div>
                  </div>
                </div>
              </div>
             
            </div>
          </div>
          <div class="col-md-2">
             <div class="ftco-footer-widget mb-4 ml-md-4">
              <h2 class="ftco-heading-2">Site Links</h2>
              <ul class="list-unstyled">
                <li><a href="{% url 'Home:start_page' %}" class="py-2 d-block">Home</a></li>
                <li><a href="{% url  'Accounts:register'%}" class="py-2 d-block">Register</a></li>
                <li><a href="{% url  'Accounts:login'%}" class="py-2 d-block">Login</a></li>
              </ul>
            </div>
          </div>
          <div class="col-md-3">
            <div class="ftco-footer-widget mb-4">
            	<h2 class="ftco-heading-2">Have a Questions?</h2>
            	<div class="block-23 mb-3">
	              <ul>
	                <li><span class="icon icon-map-marker"></span><span class="text">Nairobi Kenya</span></li>
	                <li><a href="#"><span class="icon icon-phone"></span><span class="text">+254 700 000 000</span></a></li>
	                <li><a href="#"><span class="icon icon-envelope"></span><span class="text">info@yourdomain.com</span></a></li>
	              </ul>
	            </div>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-md-12 text-center">

            <p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
  Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="icon-heart" aria-hidden="true"></i> by <a href="https://colorlib.com" class="hidden" style="visibility: hidden" target="_blank">Colorlib</a>
  <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
          </div>
        </div>
      </div>
    </footer>



  <!-- loader -->
  <div id="ftco-loader" class="show fullscreen"><svg class="circular" width="48px" height="48px"><circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/><circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#F96D00"/></svg></div>


  <script src="{% static 'start_page/js/jquery.min.js' %}"></script>
  <script src="{% static 'start_page/js/jquery-migrate-3.0.1.min.js' %}"></script>
  <script src="{% static 'start_page/js/popper.min.js' %}"></script>
  <script src="{% static 'start_page/js/bootstrap.min.js' %}"></script>
  <script src="{% static 'start_page/js/jquery.easing.1.3.js' %}"></script>
  <script src="{% static 'start_page/js/jquery.waypoints.min.js' %}"></script>
  <script src="{% static 'start_page/js/jquery.stellar.min.js' %}"></script>
  <script src="{% static 'start_page/js/owl.carousel.min.js' %}"></script>
  <script src="{% static 'start_page/js/jquery.magnific-popup.min.js' %}"></script>
  <script src="{% static 'start_page/js/aos.js' %}"></script>
  <script src="{% static 'start_page/js/jquery.animateNumber.min.js' %}"></script>
  <script src="{% static 'start_page/js/bootstrap-datepicker.js' %}"></script>
  <script src="{% static 'start_page/js/jquery.timepicker.min.js' %}"></script>
  <script src="{% static 'start_page/js/scrollax.min.js' %}"></script>
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false"></script>
  <script src="{% static 'start_page/js/google-map.js' %}"></script>
  <script src="{% static 'start_page/js/main.js' %}"></script>

  </body>
</html>