BloodDonationSystem/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('backend', admin.site.urls),
    path('donator/', include('donator.urls')),
    path('receiver/', include('receiver.urls')),
    path('accounts/', include('accounts.urls')),
    path('', include('home.urls')),
]

accounts/urls.py
from django.urls import path, include

from accounts.views import register, DashboardView, DonatorReceiverDashboardView, loginRequest

app_name = 'Accounts'
urlpatterns = [
    path('register', register, name='register'),
    path('login', loginRequest, name='login'),
    path('dashboard', DashboardView.as_view(), name='dashboard'),
    path('user_dashboard', DonatorReceiverDashboardView.as_view(), name='user_dashboard')
]

donator/urls.py
from django.urls import path

from donator.views import indexView, new_donor, DonatorsView, donate, newDonation, MyDonationView

app_name = 'Donator'
urlpatterns = [
    path('test', indexView),
    path('new_donor', new_donor, name='new_donor'),
    path('donators', DonatorsView.as_view(), name='donators'),
    path('my_donations', MyDonationView.as_view(), name='my_donations'),
    path('<receiver>/donate', donate, name='donate'),
    path('new_donation', newDonation, name='new_donation')

]

home/urls.py
from django.urls import path

from home.views import IndexView
app_name = 'Home'
urlpatterns = [
    path('',IndexView.as_view(),name='start_page')
]

receiver/urls.py
from django.urls import path

from receiver.views import index, new_receiver, ReceiverView

app_name = 'Receiver'
urlpatterns = [
    path('receivers', ReceiverView.as_view(), name='receivers'),
    path('new_receiver', new_receiver, name='new_receiver')

]

templates/admin_sidebar.html
    <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

        <!-- Sidebar - Brand -->
        <a class="sidebar-brand d-flex align-items-center justify-content-center" href="index.html">
            <div class="sidebar-brand-icon rotate-n-15">
                <i class="fas fa-laugh-wink"></i>
            </div>
            <div class="sidebar-brand-text mx-3">SB Admin <sup>2</sup></div>
        </a>

        <!-- Divider -->
        <hr class="sidebar-divider my-0">

        <!-- Nav Item - Dashboard -->
        <li class="nav-item active">
            <a class="nav-link" href="{% url 'Accounts:dashboard' %}">
                <i class="fas fa-fw fa-tachometer-alt"></i>
                <span>Dashboard</span></a>
        </li>

        <!-- Divider -->
        <hr class="sidebar-divider">



        <!-- Nav Item - Pages Collapse Menu -->
        <li class="nav-item">
            <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo"
               aria-expanded="true" aria-controls="collapseTwo">
                <i class="fas fa-fw fa-cog"></i>
                <span>Donators</span>
            </a>
            <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
                <div class="bg-white py-2 collapse-inner rounded">
                    <a class="collapse-item" href="{% url 'Donator:new_donor' %}">New Donator</a>
                    <a class="collapse-item" href="{% url 'Donator:donators' %}">Donators</a>
                </div>
            </div>
        </li>

        <!-- Nav Item - Utilities Collapse Menu -->
        <li class="nav-item">
            <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseUtilities"
               aria-expanded="true" aria-controls="collapseUtilities">
                <i class="fas fa-fw fa-wrench"></i>
                <span>Receiver</span>
            </a>
            <div id="collapseUtilities" class="collapse" aria-labelledby="headingUtilities"
                 data-parent="#accordionSidebar">
                <div class="bg-white py-2 collapse-inner rounded">
                    <a class="collapse-item" href="{% url 'Receiver:new_receiver' %}">New Receiver</a>
                    <a class="collapse-item" href="{% url  'Receiver:receivers' %}">Receivers</a>
                </div>
            </div>
        </li>
        <!-- Sidebar Toggler (Sidebar) -->
        <div class="text-center d-none d-md-inline">
            <button class="rounded-circle border-0" id="sidebarToggle"></button>
        </div>

    </ul>

templates/auth.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Blood Donation System Register</title>

  <!-- Custom fonts for this template-->
  <link href="{% static 'admin/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

  <!-- Custom styles for this template-->
  <link href="{% static 'admin/css/sb-admin-2.css' %}" rel="stylesheet">

    {% block style %}

    {% endblock %}
</head>

<body class="bg-gradient-primary">

  <div class="container">

   {% block content%}


      {% endblock %}

  </div>

  <!-- Bootstrap core JavaScript-->
  <script src="{% static 'admin/vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'admin/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Core plugin JavaScript-->
  <script src="{% static 'admin/vendor/jquery-easing/jquery.easing.min.js' %}"></script>

  <!-- Custom scripts for all pages-->
  <script src="{% static 'admin/js/sb-admin-2.min.js' %}"></script>

</body>

</html>

templates/receiver_donator_sidebar.html
    <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

        <!-- Sidebar - Brand -->
        <a class="sidebar-brand d-flex align-items-center justify-content-center" href="index.html">
            <div class="sidebar-brand-icon rotate-n-15">
                <i class="fas fa-laugh-wink"></i>
            </div>
            <div class="sidebar-brand-text mx-3">SB Admin <sup>2</sup></div>
        </a>

        <!-- Divider -->
        <hr class="sidebar-divider my-0">

        <!-- Nav Item - Dashboard -->
        <li class="nav-item active">
            <a class="nav-link" href="{% url 'Accounts:user_dashboard' %}">
                <i class="fas fa-fw fa-tachometer-alt"></i>
                <span>Dashboard</span></a>
        </li>

        <!-- Divider -->
        <hr class="sidebar-divider">

        <!-- Nav Item - Tables -->
        <li class="nav-item">
            <a class="nav-link" href="{% url 'Receiver:receivers' %}">
                <i class="fas fa-fw fa-table"></i>
                <span>Receivers</span></a>
        </li>


        <!-- Nav Item - Tables -->
        <li class="nav-item">
            <a class="nav-link" href="{% url 'Donator:my_donations' %}">
                <i class="fas fa-fw fa-table"></i>
                <span>My Donations</span></a>
        </li>


        <!-- Sidebar Toggler (Sidebar) -->
        <div class="text-center d-none d-md-inline">
            <button class="rounded-circle border-0" id="sidebarToggle"></button>
        </div>

    </ul>